import oracledb
import logging 

# 🔐 Configuración (ajusta con tus datos)
DB_USER = "system"
DB_PASSWORD = "system"
DB_DSN = "localhost:1521/XEPDB1"  # ejemplo típico Oracle XE


def conectar_db():
    try:
        conn = oracledb.connect(
            user=DB_USER,
            password=DB_PASSWORD,
            dsn=DB_DSN
        )
        logging.info("Conexión a Oracle exitosa")
        return conn
    except Exception as e:
        logging.error(f"Error conectando a Oracle: {e}")
        raise

def crear_tabla():
    conn = conectar_db()
    cursor = conn.cursor()

    try:
        cursor.execute("""
        BEGIN
            EXECUTE IMMEDIATE '
                CREATE TABLE productos (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    seccion VARCHAR2(100),
                    subcategoria VARCHAR2(100),
                    nombre VARCHAR2(500),
                    precio VARCHAR2(50),
                    link VARCHAR2(1000) UNIQUE,
                    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            ';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN
                    RAISE;
                END IF;
        END;
        """)

        conn.commit()
        logging.info("Tabla verificada/creada")

    finally:
        cursor.close()
        conn.close()
        
def insertar_productos(productos):
    conn = conectar_db()
    cursor = conn.cursor()

    try:
        data = [
            (
                p["seccion"],
                p["subcategoria"],
                p["nombre"],
                p["precio"],
                p["link"]
            )
            for p in productos
        ]

        cursor.executemany("""
            INSERT INTO productos (seccion, subcategoria, nombre, precio, link)
            VALUES (:1, :2, :3, :4, :5)
        """, data)

        conn.commit()
        logging.info(f"{len(productos)} productos insertados")

    except Exception as e:
        logging.warning(f"Error insertando (posibles duplicados): {e}")

    finally:
        cursor.close()
        conn.close()        